/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 model.glb
Author: iSteven (https://sketchfab.com/OneSteven)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/maserati-mc20-754184151ba047978014c9ba56c8ac7a
Title: Maserati MC20
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { angleToRadians } from "../../utils/angle";

export function Car() {
  const { nodes, materials } = useGLTF("/models/car/model.glb");
  return (
    <group
      dispose={null}
      scale={0.7}
      position={[0, 0.5, -2]}
      rotation={[0, angleToRadians(45), 0]}
    >
      <group scale={0.01}>
        <group
          position={[207.24, 0, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.mesh016_light_e_0.geometry}
            material={materials.light_e}
          />
          <mesh
            geometry={nodes.mesh016_light_0.geometry}
            material={materials.light}
          />
        </group>
        <group
          position={[303.51, 22.49, 148.63]}
          rotation={[-Math.PI / 2, 0, -0.3]}
          scale={100}
        >
          <mesh
            geometry={nodes.wheel_tire_0.geometry}
            material={materials.tire}
          />
          <mesh
            geometry={nodes.wheel_disc_0.geometry}
            material={materials.disc}
          />
          <mesh
            geometry={nodes.wheel_rim_0.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.wheel_chrome_0.geometry}
            material={materials.chrome}
          />
        </group>
        <group
          position={[110.96, 22.49, 148.63]}
          rotation={[-Math.PI / 2, 0, 2.83]}
          scale={100}
        >
          <mesh
            geometry={nodes.wheel002_tire_0.geometry}
            material={materials.tire}
          />
          <mesh
            geometry={nodes.wheel002_disc_0.geometry}
            material={materials.disc}
          />
          <mesh
            geometry={nodes.wheel002_rim_0.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.wheel002_chrome_0.geometry}
            material={materials.chrome}
          />
        </group>
        <group
          position={[303.51, 22.49, -155.86]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.wheel003_tire_0.geometry}
            material={materials.tire}
          />
          <mesh
            geometry={nodes.wheel003_disc_0.geometry}
            material={materials.disc}
          />
          <mesh
            geometry={nodes.wheel003_rim_0.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.wheel003_chrome_0.geometry}
            material={materials.chrome}
          />
        </group>
        <group
          position={[110.96, 22.49, -155.86]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        >
          <mesh
            geometry={nodes.wheel004_tire_0.geometry}
            material={materials.tire}
          />
          <mesh
            geometry={nodes.wheel004_disc_0.geometry}
            material={materials.disc}
          />
          <mesh
            geometry={nodes.wheel004_rim_0.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.wheel004_chrome_0.geometry}
            material={materials.chrome}
          />
        </group>
        <group
          position={[-244.36, 0, -149.05]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        >
          <mesh
            geometry={nodes.mesh027_light_e_0.geometry}
            material={materials.light_e}
          />
          <mesh
            geometry={nodes.mesh027_light_0.geometry}
            material={materials.light}
          />
        </group>
        <group
          position={[-340.64, 22.49, -297.68]}
          rotation={[-Math.PI / 2, 0, 2.84]}
          scale={100}
        >
          <mesh
            geometry={nodes.wheel005_tire_0.geometry}
            material={materials.tire}
          />
          <mesh
            geometry={nodes.wheel005_disc_0.geometry}
            material={materials.disc}
          />
          <mesh
            geometry={nodes.wheel005_rim_0.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.wheel005_chrome_0.geometry}
            material={materials.chrome}
          />
        </group>
        <group
          position={[-148.09, 22.49, -297.68]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 10]}
          scale={100}
        >
          <mesh
            geometry={nodes.wheel006_tire_0.geometry}
            material={materials.tire}
          />
          <mesh
            geometry={nodes.wheel006_disc_0.geometry}
            material={materials.disc}
          />
          <mesh
            geometry={nodes.wheel006_rim_0.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.wheel006_chrome_0.geometry}
            material={materials.chrome}
          />
        </group>
        <group
          position={[-340.64, 22.49, 6.82]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        >
          <mesh
            geometry={nodes.wheel007_tire_0.geometry}
            material={materials.tire}
          />
          <mesh
            geometry={nodes.wheel007_disc_0.geometry}
            material={materials.disc}
          />
          <mesh
            geometry={nodes.wheel007_rim_0.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.wheel007_chrome_0.geometry}
            material={materials.chrome}
          />
        </group>
        <group
          position={[-148.09, 22.49, 6.82]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.wheel008_tire_0.geometry}
            material={materials.tire}
          />
          <mesh
            geometry={nodes.wheel008_disc_0.geometry}
            material={materials.disc}
          />
          <mesh
            geometry={nodes.wheel008_rim_0.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.wheel008_chrome_0.geometry}
            material={materials.chrome}
          />
        </group>
        <mesh
          geometry={nodes.mesh001_paint_0.geometry}
          material={materials.paint}
          position={[207.24, 0, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.mesh003_bumpa_0.geometry}
          material={materials.bumpa}
          position={[207.24, 0, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.mesh004_chrome_0.geometry}
          material={materials.chrome}
          position={[207.24, 0, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.mesh005_mlack_0.geometry}
          material={materials.mlack}
          position={[207.24, 0, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.mesh006_glack_0.geometry}
          material={materials.glack}
          position={[207.24, 0, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.mesh010_red2_0.geometry}
          material={materials.red2}
          position={[207.24, 0, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.mesh011_FrontColor_0.geometry}
          material={materials.FrontColor}
          position={[207.24, 0, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.mesh013_red2_0.geometry}
          material={materials.red2}
          position={[207.24, 0, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={
            nodes.mesh015_M_2022_Maserati_MC20_Default_Material_0.geometry
          }
          material={materials.M_2022_Maserati_MC20_Default_Material}
          position={[207.24, 0, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.mesh017_paint_b_0.geometry}
          material={materials.paint_b}
          position={[207.24, 0, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Vert_cali_0.geometry}
          material={materials.cali}
          position={[303.51, 22.49, 148.63]}
          rotation={[-Math.PI / 2, 0, -0.3]}
          scale={100}
        />
        <mesh
          geometry={nodes.mesh008_red_0.geometry}
          material={materials.material_15}
          position={[207.24, 0, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Vert001_cali_0.geometry}
          material={materials.cali}
          position={[110.96, 22.49, 148.63]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 10]}
          scale={[-100, 100, 100]}
        />
        <mesh
          geometry={nodes.Vert002_cali_0.geometry}
          material={materials.cali}
          position={[303.51, 22.49, -155.86]}
          rotation={[-2.54, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Vert003_cali_0.geometry}
          material={materials.cali}
          position={[110.96, 22.49, -155.86]}
          rotation={[-2.54, 0, 0]}
          scale={[-100, 100, 100]}
        />
        <mesh
          geometry={nodes.mesh018_paint001_0.geometry}
          material={materials["paint.001"]}
          position={[-244.36, 0, -149.05]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        />
        <mesh
          geometry={nodes.mesh019_bumpa_0.geometry}
          material={materials.bumpa}
          position={[-244.36, 0, -149.05]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        />
        <mesh
          geometry={nodes.mesh020_chrome_0.geometry}
          material={materials.chrome}
          position={[-244.36, 0, -149.05]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        />
        <mesh
          geometry={nodes.mesh021_mlack_0.geometry}
          material={materials.mlack}
          position={[-244.36, 0, -149.05]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        />
        <mesh
          geometry={nodes.mesh022_glack_0.geometry}
          material={materials.glack}
          position={[-244.36, 0, -149.05]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        />
        <mesh
          geometry={nodes.mesh023_red2_0.geometry}
          material={materials.red2}
          position={[-244.36, 0, -149.05]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        />
        <mesh
          geometry={nodes.mesh024_FrontColor_0.geometry}
          material={materials.FrontColor}
          position={[-244.36, 0, -149.05]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        />
        <mesh
          geometry={nodes.mesh025_red2_0.geometry}
          material={materials.red2}
          position={[-244.36, 0, -149.05]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        />
        <mesh
          geometry={
            nodes.mesh026_M_2022_Maserati_MC20_Default_Material_0.geometry
          }
          material={materials.M_2022_Maserati_MC20_Default_Material}
          position={[-244.36, 0, -149.05]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        />
        <mesh
          geometry={nodes.mesh028_paint_b_0.geometry}
          material={materials.paint_b}
          position={[-244.36, 0, -149.05]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        />
        <mesh
          geometry={nodes.Vert004_cali_0.geometry}
          material={materials.cali}
          position={[-340.64, 22.49, -297.68]}
          rotation={[-Math.PI / 2, 0, 2.84]}
          scale={100}
        />
        <mesh
          geometry={nodes.mesh029_red_0.geometry}
          material={materials.material_15}
          position={[-244.36, 0, -149.05]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        />
        <mesh
          geometry={nodes.Vert005_cali_0.geometry}
          material={materials.cali}
          position={[-148.09, 22.49, -297.68]}
          rotation={[-Math.PI / 2, 0, 2.83]}
          scale={[-100, 100, 100]}
        />
        <mesh
          geometry={nodes.Vert006_cali_0.geometry}
          material={materials.cali}
          position={[-340.64, 22.49, 6.82]}
          rotation={[-0.61, 0, -Math.PI]}
          scale={100}
        />
        <mesh
          geometry={nodes.Vert007_cali_0.geometry}
          material={materials.cali}
          position={[-148.09, 22.49, 6.82]}
          rotation={[-0.61, 0, -Math.PI]}
          scale={[-100, 100, 100]}
        />
        <mesh
          geometry={nodes.mesh012_glass_l_0.geometry}
          material={materials.glass_l}
          position={[207.24, 0, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.mesh007_glass_0.geometry}
          material={materials.glass}
          position={[207.24, 0, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.mesh009_grill_0.geometry}
          material={materials.grill}
          position={[207.24, 0, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.mesh002_bhrome_0.geometry}
          material={materials.bhrome}
          position={[207.24, 0, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.mesh014_carbon_0.geometry}
          material={materials.carbon}
          position={[207.24, 0, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.mesh030_glass_l_0.geometry}
          material={materials.glass_l}
          position={[-244.36, 0, -149.05]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        />
        <mesh
          geometry={nodes.mesh031_glass_0.geometry}
          material={materials.glass}
          position={[-244.36, 0, -149.05]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        />
        <mesh
          geometry={nodes.mesh032_grill_0.geometry}
          material={materials.grill}
          position={[-244.36, 0, -149.05]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        />
        <mesh
          geometry={nodes.mesh033_bhrome_0.geometry}
          material={materials.bhrome}
          position={[-244.36, 0, -149.05]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        />
        <mesh
          geometry={nodes.mesh034_carbon_0.geometry}
          material={materials.carbon}
          position={[-244.36, 0, -149.05]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/car/model.glb");
